default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: stone_development

test:
  <<: *default
  database: stone_test

staging:
  <<: *default
  database: staging_production
  password:

production:
  <<: *default
  database: stone_development
  password: <%= ENV['STONE_DATABASE_PASSWORD'] %>
